# The numpy.random package 

<h2>Assignment 2018 for Programming for Data Analysis - Investigation into numpy.random</h2>

There are four distinct tasks to be carried out in this investigation.
<ol><li>Explain the overall purpose of the numpy.random package.</li>
<li>Explain the use of the “Simple random data” and “Permutations” functions.</li>
<li>Explain the use and purpose of at least five “Distributions” functions.</li>
<li>Explain the use of seeds in generating pseudorandom numbers.</li></ol>

<hr>

<h4>1. Explanation of the overall purpose of the numpy.random package<h4>
Numpy.random is a sub package of the NumPy library for Python. NumPy, which is short for Numerical Python, is a library which contains large, multidimensional arrays and matrices as well as a collection of high-level mathematical routines to process these arrays. NumPy enriches Python and ensures efficient calculation. To attempt a NumPy function through core Python would require extensive amounts of custom code. 

Random numbers - and the ability to generate random numbers - are an important part of data analysis. The numpy.random sub package can generate random, or to be more accurate, pseudorandom numbers - pseudorandom because numpy.random arrays are determined by an initial value known as a seed. As a result, pseudorandom number generators can never be considered truely random, but that is more a theoretical point. In terms of statistics and probability, pseudorandom number generators are more than sufficient. 

The purpose of the numpy.random package is to provide us with a way to generate and analyze pseudorandom number arrays and matrices. 

<h4>2. Explanation of the use of "Simple random data" and "Permutations" functions.</h4>

<h5>Simple Random Data</h5>

Simple random data is a collection of sub-routines within the numpy.random routine. At it's most basic, the simple random data routines are variations on the essential premise of numpy.random which is concerned with the creation of values from probabiliity distributions. 

Take the numpy.random.rand function as an example. numpy.random.rand is a convenience function that creates an array of specified shape and fills it with random values.

In [1]:
# Import Libraries
import numpy as np #import numpy

In [2]:
np.random.rand(4) #create a basic 1D array of 4 rows and 1 column

array([ 0.62494673,  0.4323023 ,  0.55447678,  0.39753918])

In [3]:
np.random.rand(4) #re-running same line of code gives a random result

array([ 0.97665546,  0.61512028,  0.32909621,  0.94571042])

In [4]:
np.random.rand(4,5) #to run 2d array of random values

array([[ 0.57044976,  0.461307  ,  0.08889397,  0.81468376,  0.72076702],
       [ 0.14483974,  0.91497191,  0.04901292,  0.32395342,  0.893191  ],
       [ 0.340149  ,  0.54674514,  0.23262032,  0.27048067,  0.83847688],
       [ 0.16714158,  0.82117912,  0.4471407 ,  0.35039954,  0.95301748]])

The second sub routine in the simple random data collection we can look at is numpy.random.sample - which returns random floats in the half open interval [0.0, 1.0).

In [7]:
np.random.random_sample(4)

array([ 0.28584039,  0.32871289,  0.99505286,  0.42005845])

Many of the sub-routines in numpy.random perform similar tasks, but random.random_sample takes it one step further and is just an alias for the functions random.random, random.ranf, and random.rand. 

In [13]:
np.random.random_sample is np.random.ranf is np.random.random

True

The only difference between random.random_sample and random.rand is that the shapes of the output array in random.rand are separate arguments compared to a signle tupel in random.random_sample.

<h5>Permutations Functions